services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sghss-sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
